### ISSUE TITLE
Make sure back-end isn't throwing any random error(s) for other game modes

### ISSUE THREAD

**Issue by mandishshah** [LOLQueen/back-end#15]
Refer to pull request: https://github.com/LOLQueen/back-end/pull/13

Just make sure other game modes, such as Twisted Treeline, aren't causing our back-end to throw any expected errors

**Comment by RSNara** [comment]
This too vague. Can you give me an instance or steps to reproduce the errors?

**Comment by Bbowen100** [comment]
What I think Mandish is talking about is you can have several types of custom games with bots; which means that the object wont return any fellow summoners and the app will break

**Comment by RSNara** [comment]
@Bbowen100 the app shouldn't break. PR #13 fixes that issue.

**Comment by Bbowen100** [comment]
yeah thats true

**Comment by mandishshah** [comment]
Was just wondering if all different cases were being considered or not, sounds good though
